# Generated by Django 3.2.11 on 2022-02-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('region', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DifferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('difference', models.IntegerField()),
                ('models', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GiftsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('entity', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('loyalty_program', models.CharField(choices=[('konkurs', 'Конкурс'), ('cashback', 'Кэшбэк')], max_length=250)),
                ('active', models.BooleanField()),
                ('branch', models.SmallIntegerField()),
                ('region', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code_1c', models.CharField(max_length=11)),
                ('region', models.CharField(max_length=7)),
                ('bonuses', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('operation_type', models.PositiveSmallIntegerField()),
                ('event_type', models.PositiveSmallIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('count', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.person')),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('count', models.PositiveSmallIntegerField()),
                ('gift_id', models.CharField(max_length=36)),
                ('nominal', models.IntegerField()),
                ('created', models.DateField()),
                ('loyalty_program', models.CharField(choices=[('k', 'К'), ('c', 'К')], max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.person')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
